name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release, Dist]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Create Project Files
      run: |
       cd Scripts
       Invoke-Expression ".\GenerateProjectsWindows.bat"
       cd ..
    - name: Set up msbuild
      uses: microsoft/setup-msbuild@v2
    - name: Build
      run: msbuild PAPI.sln -t:rebuild -property:Configuration=${{ matrix.config }} -property:Platform=Win64
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: PAPI Windows x64 ${{ matrix.config }}
        path: Build/PAPI/${{ matrix.config }}-windows-x86_64\

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [Debug, Release, Dist]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    - name: Create Project Files
      run: |
       cd Scripts
       bash GenerateProjectsLinux.sh
       cd ..
    - name: String Case
      id: string
      uses: ASzc/change-string-case-action@v6
      with:
        string: ${{ matrix.config }}
    - name: Set up make
      uses: pkgxdev/setup@v1
      with:
        +: gcc
    - name: Build
      run: make SHELL='sh -x' config=${{ steps.string.outputs.lowercase }}_linux -j8 # 8 jobs is hopefully a good middle-ground when we don't know how many cores the machine has.
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: PAPI Linux x64 ${{ matrix.config }}
        path: ./Build/PAPI/${{ matrix.config }}-linux-x86_64/
